version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/freelance-ops-agent:latest
    container_name: agent-${COLOR}
    restart: always
    ports:
      - "${APP_PORT}:8000"
    environment:
      - MONGO_URL=mongodb://agent-mongodb:27017/agent_db
      - KAFKA_BOOTSTRAP_SERVERS=agent-kafka:9092
      - FAISS_INDEX_PATH=/data/faiss_index
    volumes:
      - ./logs_data:/src/src/logs_data
      - ./faiss_data:/data/faiss_index
    env_file:
      - .env
    networks:
      - agent-network

  worker:
    image: ${DOCKER_USERNAME}/freelance-ops-agent:latest
    container_name: agent-worker-${COLOR}
    restart: always
    entrypoint: ["poetry", "run", "python", "-m", "src.worker"]
    environment:
      - MONGO_URL=mongodb://agent-mongodb:27017/agent_db
      - KAFKA_BOOTSTRAP_SERVERS=agent-kafka:9092
      - FAISS_INDEX_PATH=/data/faiss_index
    volumes:
      - ./faiss_data:/data/faiss_index
    env_file:
      - .env
    networks:
      - agent-network

networks:
  agent-network:
    external: true