package com.freelanceops.backend.domain.agentrun.dto;

import java.util.Set;

/** Generated from the pinned 1.0.0 catalog; identifiers are never paths or tool names. */
public final class BuiltinSkillIds {
    private BuiltinSkillIds() { }
    public static final Set<String> ALL = Set.of(
        "dev-requirements-acceptance",
        "dev-bug-triage",
        "dev-api-contract",
        "dev-responsive-frontend",
        "dev-accessibility-review",
        "dev-test-design",
        "dev-refactor-plan",
        "dev-performance-triage",
        "dev-security-review",
        "dev-release-handoff",
        "design-creative-brief",
        "design-brand-direction",
        "design-wireframe-flows",
        "design-ui-system",
        "design-usability-review",
        "design-presentation-storyboard",
        "design-print-preflight",
        "design-asset-handoff",
        "video-script-shotlist",
        "video-edit-plan",
        "video-shortform-repurpose",
        "video-subtitle-qc",
        "video-audio-cleanup-plan",
        "video-delivery-qc",
        "writing-article-draft",
        "writing-copyedit-factcheck",
        "writing-landing-copy",
        "writing-technical-docs",
        "writing-case-study",
        "writing-email-sequence",
        "writing-proposal",
        "translation-faithful",
        "translation-transcreation",
        "translation-subtitles",
        "translation-glossary",
        "translation-localization-qa",
        "marketing-seo-brief",
        "marketing-onpage-seo",
        "marketing-social-calendar",
        "marketing-ad-variants",
        "marketing-email-campaign",
        "marketing-funnel-review",
        "marketing-analytics-readout",
        "marketing-experiment-plan",
        "ops-scope-statement",
        "ops-estimate-budget",
        "ops-milestone-plan",
        "ops-client-intake",
        "ops-meeting-actions",
        "ops-change-request",
        "ops-weekly-status",
        "ops-invoice-draft",
        "ops-project-handover",
        "ops-retainer-capacity",
        "research-source-brief",
        "research-competitor-comparison",
        "research-interview-synthesis",
        "research-survey-design",
        "research-data-cleaning",
        "research-insight-report"
    );
}
